name = "nuansa-web"
main = "src/index.tsx"
compatibility_date = "2024-03-20"
account_id = "ecd009a3d2a4392730f427e7a94ec32f"

[[d1_databases]]
binding = "DB"
database_name = "nuansa-tenant-db"
database_id = "cff9dfe9-92ed-47cd-a73f-1571535d3a00"
